variables:
  #PIP_EXTRA_INDEX_URL: https://nexus.patrikdufresne.com/repository/pypi/simple
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
               -Dorg.slf4j.simpleLogger.showDateTime=true
               -Djava.awt.headless=true
               -Dmaven.repo.local=.m2/repository"
  APT_DEV_BUSTER: https://nexus.ikus-soft.com/repository/minarca-apt-dev-buster/
  APT_DEV_STRETCH: https://nexus.ikus-soft.com/repository/minarca-apt-dev-stretch/
  APT_RELEASE_BUSTER: https://nexus.ikus-soft.com/repository/minarca-apt-release-buster/
  APT_RELEASE_STRETCH: https://nexus.ikus-soft.com/repository/minarca-apt-release-stretch/
  
stages:
- prebuild
- build
- test-package
- publish
- deploy
- test-integration

prebuild:  
  image: docker:stable
  stage: prebuild
  script:
  - apk add make bash
  - make prebuild

# TODO Split this by python version and OS.
.make: &make
  stage: build
  image: $DOCKER_REGISTRY/pdsl/minarca-prebuild-$IMAGE:$CI_PIPELINE_IID
  script:
  - make $TARGET

test-server_stretch_python2: 
  <<: *make
  variables:
    TARGET: test-server
    IMAGE: stretch-python2

test-server_stretch_python3: 
  <<: *make
  variables:
    TARGET: test-server
    IMAGE: stretch-python3
  
test-server_buster_python3: 
  <<: *make
  variables:
    TARGET: test-server
    IMAGE: buster-python3

test-quota-api_stretch_python2:
  <<: *make
  variables:
    TARGET: test-quota-api
    IMAGE: stretch-python2

test-quota-api_buster_python3:
  <<: *make
  variables:
    TARGET: test-quota-api
    IMAGE: buster-python3

test-client_stretch:
  <<: *make
  variables:
    TARGET: test-client
    IMAGE: stretch-java8

test-client_windows:
  <<: *make
  variables:
    TARGET: test-client
    IMAGE: windows-java8
    SONAR_URL: ""

build-client:
  <<: *make
  variables:
    TARGET: build-client
    IMAGE: stretch-java8
  artifacts:
    paths:
    - minarca-client*.exe
    - minarca-client*.deb

build-server_stretch:
  <<: *make
  variables:
    TARGET: build-server
    IMAGE: stretch-buildpackage
  artifacts:
    paths:
    - minarca-server_*.deb
    
build-server_buster:
  <<: *make
  variables:
    TARGET: build-server
    IMAGE: buster-buildpackage
  artifacts:
    paths:
    - minarca-server_*.deb

test-server_stretch_deb:
  stage: test-package
  image: buildpack-deps:stretch
  script: 
  - export MINARCA_DEB_FILE=$(ls -1 ./minarca-server_*+stretch_amd64.deb)
  - bash ./tests/install-server-deb.sh $MINARCA_DEB_FILE
  
test-server_buster_deb:
  stage: test-package
  image: buildpack-deps:buster
  script:
  - export MINARCA_DEB_FILE=$(ls -1 ./minarca-server_*+buster_amd64.deb)
  - bash ./tests/install-server-deb.sh $MINARCA_DEB_FILE

test-client_stretch_deb:
  stage: test-package
  image: buildpack-deps:stretch
  script:
  - export MINARCA_DEB_FILE=$(ls -1 ./minarca-client*.deb)
  - bash ./tests/install-client-deb.sh

test-client_buster_deb:
  stage: test-package
  image: buildpack-deps:buster
  script:
  - export MINARCA_DEB_FILE=$(ls -1 ./minarca-client*.deb)
  - bash ./tests/install-client-deb.sh

test-client_windows_exe:
  stage: test-package
  image: buildpack-deps:stretch
  script:
  - export MINARCA_EXE_FILE=$(ls -1 ./minarca-client*.exe)
  - bash ./tests/install-client-win.sh

publish-server:
  stage: publish
  except:
  - tags
  script:
  # Publish to kalo
  - eval $(ssh-agent -s)
  - echo "$KALO_WWWDATA_PRIVATEKEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - scp -o StrictHostKeyChecking=no ./minarca-server_*.deb www-data@kalo.patrikdufresne.com:/var/www/patrikdufresne/archive/minarca/nightly/

publish-apt:
  stage: publish
  image: buildpack-deps:buster
  script: |
    # Publish client and server to APT repo.
    # Minarca Server Stretch
    export MINARCA_DEB_FILE=$(ls -1 ./minarca-server_*+stretch_amd64.deb)
    curl -u "$NEXUS_USR:$NEXUS_PWD" -H "Content-Type: multipart/form-data" --data-binary "@$MINARCA_DEB_FILE" "$APT_DEV_STRETCH"
    [ -z "$CI_COMMIT_TAG" ] || curl -u "$NEXUS_USR:$NEXUS_PWD" -H "Content-Type: multipart/form-data" --data-binary "@$MINARCA_DEB_FILE" "$APT_RELEASE_STRETCH" 
    # Minarca Server Buster
    export MINARCA_DEB_FILE=$(ls -1 ./minarca-server_*+buster_amd64.deb)
    curl -u "$NEXUS_USR:$NEXUS_PWD" -H "Content-Type: multipart/form-data" --data-binary "@$MINARCA_DEB_FILE" "$APT_DEV_BUSTER"
    [ -z "$CI_COMMIT_TAG" ] || curl -u "$NEXUS_USR:$NEXUS_PWD" -H "Content-Type: multipart/form-data" --data-binary "@$MINARCA_DEB_FILE" "$APT_RELEASE_BUSTER"
    # Minarca Client
    export MINARCA_DEB_FILE=$(ls -1 ./minarca-client*.deb)
    curl -u "$NEXUS_USR:$NEXUS_PWD" -H "Content-Type: multipart/form-data" --data-binary "@$MINARCA_DEB_FILE" "$APT_DEV_STRETCH"
    curl -u "$NEXUS_USR:$NEXUS_PWD" -H "Content-Type: multipart/form-data" --data-binary "@$MINARCA_DEB_FILE" "$APT_DEV_BUSTER"
    [ -z "$CI_COMMIT_TAG" ] || curl -u "$NEXUS_USR:$NEXUS_PWD" -H "Content-Type: multipart/form-data" --data-binary "@$MINARCA_DEB_FILE" "$APT_RELEASE_STRETCH"
    [ -z "$CI_COMMIT_TAG" ] || curl -u "$NEXUS_USR:$NEXUS_PWD" -H "Content-Type: multipart/form-data" --data-binary "@$MINARCA_DEB_FILE" "$APT_RELEASE_BUSTER"

promote-server:
  stage: publish
  only:
  - tags
  script:
  # Setup authentication
  - eval $(ssh-agent -s)
  - echo "$KALO_WWWDATA_PRIVATEKEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  # Public stretch package to kalo
  - export MINARCA_DEB_FILE=$(ls -1 ./minarca-server_*+stretch_amd64.deb)
  - scp -o StrictHostKeyChecking=no ./$MINARCA_DEB_FILE www-data@kalo.patrikdufresne.com:/var/www/patrikdufresne/archive/minarca/
  - ssh -o StrictHostKeyChecking=no www-data@kalo.patrikdufresne.com ln -fs /var/www/patrikdufresne/archive/minarca/$MINARCA_DEB_FILE /var/www/patrikdufresne/archive/minarca/minarca-server_latest+stretch_amd64.deb
  # Public buster package to kalo
  - export MINARCA_DEB_FILE=$(ls -1 ./minarca-server_*+buster_amd64.deb)
  - scp -o StrictHostKeyChecking=no ./$MINARCA_DEB_FILE www-data@kalo.patrikdufresne.com:/var/www/patrikdufresne/archive/minarca/
  - ssh -o StrictHostKeyChecking=no www-data@kalo.patrikdufresne.com ln -fs /var/www/patrikdufresne/archive/minarca/$MINARCA_DEB_FILE /var/www/patrikdufresne/archive/minarca/minarca-server_latest+buster_amd64.deb

publish-client:
  stage: publish
  environment:
    name: dev
    url: http://www.patrikdufresne.com/archive/minarca/nightly/minarca-client-${REVISION}.exe
  script:
  # Setup authentication
  - eval $(ssh-agent -s)
  - echo "$KALO_WWWDATA_PRIVATEKEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  # Publish to kalo
  - export MINARCA_DEB_FILE=$(ls -1 ./minarca-client*.deb)
  - export MINARCA_EXE_FILE=$(ls -1 ./minarca-client*.exe)
  - scp -o StrictHostKeyChecking=no $MINARCA_DEB_FILE www-data@kalo.patrikdufresne.com:/var/www/patrikdufresne/archive/minarca/nightly/
  - scp -o StrictHostKeyChecking=no $MINARCA_EXE_FILE www-data@kalo.patrikdufresne.com:/var/www/patrikdufresne/archive/minarca/nightly/

client_promote:
  stage: publish
  only:
  - tags
  environment:
    name: latest
    url: http://www.patrikdufresne.com/archive/minarca/minarca-latest-install.exe
  script:
  # Setup authentication
  - eval $(ssh-agent -s)
  - echo "$KALO_WWWDATA_PRIVATEKEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  # Publish to kalo
  - export MINARCA_DEB_FILE=$(ls -1 ./minarca-client*.deb)
  - export MINARCA_EXE_FILE=$(ls -1 ./minarca-client*.exe)
  - scp -o StrictHostKeyChecking=no $MINARCA_EXE_FILE www-data@kalo.patrikdufresne.com:/var/www/patrikdufresne/archive/minarca/
  - scp -o StrictHostKeyChecking=no $MINARCA_DEB_FILE www-data@kalo.patrikdufresne.com:/var/www/patrikdufresne/archive/minarca/
  - ssh -o StrictHostKeyChecking=no www-data@kalo.patrikdufresne.com ln -fs $(basename $MINARCA_EXE_FILE) /var/www/patrikdufresne/archive/minarca/minarca-latest-install.exe
  - ssh -o StrictHostKeyChecking=no www-data@kalo.patrikdufresne.com ln -fs $(basename $MINARCA_DEB_FILE) /var/www/patrikdufresne/archive/minarca/minarca-client_latest_all.deb

deploy_staging_sestican:
  stage: deploy
  image: ikus060/ansible
  variables:
    DIST: stretch
  environment:
    name: staging
    url: https://test.minarca.net
  script:
  - export DEB_VERSION=$(make debversion)
  - echo DEB_VERSION=$DEB_VERSION
  - curl -X POST -F token=36bae86778d901fc6b2d6453a41844 -F "ref=master" -F "variables[MINARCA_VERSION]=$DEB_VERSION" https://gitlab.com/api/v4/projects/18716492/trigger/pipeline
  
#test_link_debian_stretch:
#  image: debian:stretch
#  stage: test-integration
#  variables:
#    MINARCA_REPOSITORYNAME: test-${CI_JOB_ID}
#  script: 
#  - export MINARCA_DEB_FILE=$(ls -1 ./minarca-client*.deb)
#  - bash ./tests/install-client-deb.sh
#  - bash ./tests/link-link-deb-linux.sh
  
#test_link_debian_buster:
#  image: debian:buster
#  stage: test-integration
#  variables:
#    MINARCA_REPOSITORYNAME: test-${CI_JOB_ID}
#  script: 
#  - export MINARCA_DEB_FILE=$(ls -1 ./minarca-client*.deb)
#  - bash ./tests/install-client-deb.sh
#  - bash ./tests/link-link-deb-linux.sh

# This test is not working and fail because of issue with wine.
#test_link_win:
#  image: debian:buster
#  stage: test-integration
#  variables:
#    MINARCA_REPOSITORYNAME: test-${CI_JOB_ID}
#  allow_failure: true
#  script: 
#  - export MINARCA_EXE_FILE=$(ls -1 ./minarca-client*.exe)
#  - bash ./tests/install-client-win.sh
#  - bash ./tests/link-link-win.sh
  