variables:
  #PIP_EXTRA_INDEX_URL: https://nexus.patrikdufresne.com/repository/pypi/simple
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
               -Dorg.slf4j.simpleLogger.showDateTime=true
               -Djava.awt.headless=true
               -Dmaven.repo.local=.m2/repository"

stages:
- prebuild
- build
- test-package
- publish
- deploy
- test-integration

.prebuild:  &prebuild
  image: docker:stable
  stage: prebuild
  script:
  - "export BUILD_PATH=tools/${CI_JOB_NAME}"
  - "export TAG=$DOCKER_REGISTRY/pdsl/minarca-prebuild-${CI_JOB_NAME}:$CI_PIPELINE_IID"
  - docker login $DOCKER_REGISTRY -u $DOCKER_USR -p $DOCKER_PWD
  - docker build -t $TAG $BUILD_PATH
  - docker push $TAG

buster-python3:
  <<: *prebuild
  
buster-buildpackage:
  <<: *prebuild
  
stretch-python3:
  <<: *prebuild

stretch-python2:
  <<: *prebuild

stretch-buildpackage:
  <<: *prebuild
  
stretch-java:
  <<: *prebuild
  
windows-java:
  <<: *prebuild

# TODO Split this by python version and OS.
.test-server: &test-server
  stage: build
  image: $DOCKER_REGISTRY/pdsl/minarca-prebuild-$IMAGE:$CI_PIPELINE_IID
  script: 
  - cd minarca-server
  - export TOXENV=`tox --listenvs | grep "$TOXFACTOR" | tr '\n' ','`
  - echo TOXENV=$TOXENV
  - tox --sitepackages

test-server_stretch_python2: 
  <<: *test-server
  variables:
    IMAGE: stretch-python2

test-server_stretch_python3: 
  <<: *test-server
  variables:
    IMAGE: stretch-python3
  
test-server_buster_python3: 
  <<: *test-server
  variables:
    IMAGE: buster-python3

.test-quota-api: &test-quota-api
  stage: build
  image: $DOCKER_REGISTRY/pdsl/minarca-prebuild-$IMAGE:$CI_PIPELINE_IID
  script: 
  - cd minarca-quota-api
  - export TOXENV=`tox --listenvs | grep "$TOXFACTOR" | tr '\n' ','`
  - echo TOXENV=$TOXENV
  - tox --sitepackages

test-quota-api_stretch_python2:
  <<: *test-quota-api
  variables:
    IMAGE: stretch-python2

test-quota-api_buster_python3:
  <<: *test-quota-api
  variables:
    IMAGE: buster-python3

.test-client: &test-client
  stage: build
  image: $DOCKER_REGISTRY/pdsl/minarca-prebuild-$IMAGE:$CI_PIPELINE_IID
  script:
  - cd minarca-client
  # Get version
  - export REVISION="$(curl http://git.patrikdufresne.com/pdsl/maven-scm-version/raw/master/version.sh | bash -)"
  - echo "REVISION=$REVISION"
  # Test
  - mvn -B -Drevision=${REVISION} $MAVEN_ARGS
  # Move dist files
  - mv minarca-installation-package-deb/target/*.deb ./.. || true
  - mv minarca-installation-package/target/*.exe ./.. || true
  - mv ../minarca-installation-package-deb_*_all.deb ../minarca-client_${REVISION}_all.deb || true

test-client_stretch:
  <<: *test-client
  variables:
    IMAGE: stretch-java
    MAVEN_ARGS: -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_TOKEN clean verify org.jacoco:jacoco-maven-plugin:prepare-agent clean verify sonar:sonar

test-client_windows:
  <<: *test-client
  variables:
    IMAGE: windows-java
    MAVEN_ARGS: clean verify
  before_script:
  - (Xvfb :99 &)
  - export DISPLAY=:99

build-client:
  <<: *test-client
  variables:
    IMAGE: stretch-java
    MAVEN_ARGS: -Dsign.certs.path=/tmp/authenticode-certs.pem -Dsign.key.path=/tmp/authenticode.pem -Dsign.passphrase=$AUTHENTICODE_PASSPHRASE  clean install
  before_script:
  # Setup authenticode
  - echo "$AUTHENTICODE_CERT" | tr -d '\r' > /tmp/authenticode-certs.pem
  - echo "$AUTHENTICODE_KEY" | tr -d '\r' > /tmp/authenticode.pem
  artifacts:
    paths:
    - minarca-client*.exe
    - minarca-client*.deb

.build-server: &build-server
  stage: build
  image: $DOCKER_REGISTRY/pdsl/minarca-prebuild-$IMAGE:$CI_PIPELINE_IID
  script:
  - cd minarca-server
  - export VERSION=$(python3 setup.py --version)
  - export DIST=$(lsb_release -c -s)
  - export DEB_VERSION="$VERSION+$DIST"
  - export SETUPTOOLS_SCM_PRETEND_VERSION=$VERSION
  - export RELEASE_DATE="$(date '+%a, %d %b %Y %X') +0000"
  - sed -i "s/%VERSION%/$DEB_VERSION/" debian/changelog
  - sed -i "s/%DATE%/$RELEASE_DATE/" debian/changelog
  - DH_VIRTUALENV_INSTALL_ROOT=/opt/ dpkg-buildpackage -us -uc
  artifacts:
    paths:
    - minarca-server_*.deb

build-server_stretch:
  <<: *build-server
  variables:
    IMAGE: stretch-buildpackage
    
build-server_buster:
  <<: *build-server
  variables:
    IMAGE: buster-buildpackage

test-server_stretch_deb:
  stage: test-package
  image: debian:stretch
  script: 
  - export MINARCA_DEB_FILE=$(ls -1 ./minarca-server_*+stretch_amd64.deb)
  - bash ./tests/install-server-deb.sh $MINARCA_DEB_FILE
  
test-server_buster_deb:
  stage: test-package
  image: debian:buster
  script:
  - export MINARCA_DEB_FILE=$(ls -1 ./minarca-server_*+buster_amd64.deb)
  - bash ./tests/install-server-deb.sh $MINARCA_DEB_FILE

test-client_stretch_deb:
  stage: test-package
  image: debian:stretch
  script:
  - export MINARCA_DEB_FILE=$(ls -1 ./minarca-client*.deb)
  - bash ./tests/install-client-deb.sh

test-client_buster_deb:
  stage: test-package
  image: debian:buster
  script:
  - export MINARCA_DEB_FILE=$(ls -1 ./minarca-client*.deb)
  - bash ./tests/install-client-deb.sh

test-client_windows_exe:
  stage: test-package
  image: debian:stretch
  script:
  - export MINARCA_EXE_FILE=$(ls -1 ./minarca-client*.exe)
  - bash ./tests/install-client-win.sh

publish-server:
  stage: publish
  except:
  - tags
  script:
  # Publish to kalo
  - eval $(ssh-agent -s)
  - echo "$KALO_WWWDATA_PRIVATEKEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - scp -o StrictHostKeyChecking=no ./minarca-server_*.deb www-data@kalo.patrikdufresne.com:/var/www/patrikdufresne/archive/minarca/nightly/

promote-server:
  stage: publish
  only:
  - tags
  script:
  # Setup authentication
  - eval $(ssh-agent -s)
  - echo "$KALO_WWWDATA_PRIVATEKEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  # Publish to kalo
  - export MINARCA_DEB_STRETCH=$(ls -1 minarca-server_*_stretch.deb)
  - scp -o StrictHostKeyChecking=no ./$MINARCA_DEB_STRETCH www-data@kalo.patrikdufresne.com:/var/www/patrikdufresne/archive/minarca/
  - ssh -o StrictHostKeyChecking=no www-data@kalo.patrikdufresne.com ln -fs /var/www/patrikdufresne/archive/minarca/$MINARCA_DEB_STRETCH /var/www/patrikdufresne/archive/minarca/minarca-server_stretch_amd64.deb
  - export MINARCA_DEB_BUSTER=$(ls -1 minarca-server_*_buster.deb)
  - scp -o StrictHostKeyChecking=no ./$MINARCA_DEB_BUSTER www-data@kalo.patrikdufresne.com:/var/www/patrikdufresne/archive/minarca/
  - ssh -o StrictHostKeyChecking=no www-data@kalo.patrikdufresne.com ln -fs /var/www/patrikdufresne/archive/minarca/$MINARCA_DEB_BUSTER /var/www/patrikdufresne/archive/minarca/minarca-server_buster_amd64.deb

publish-client:
  stage: publish
  environment:
    name: dev
    url: http://www.patrikdufresne.com/archive/minarca/nightly/minarca-client-${REVISION}.exe
  script:
  # Setup authentication
  - eval $(ssh-agent -s)
  - echo "$KALO_WWWDATA_PRIVATEKEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  # Publish to kalo
  - export MINARCA_DEB_FILE=$(ls -1 ./minarca-client*.deb)
  - export MINARCA_EXE_FILE=$(ls -1 ./minarca-client*.exe)
  - scp -o StrictHostKeyChecking=no $MINARCA_DEB_FILE www-data@kalo.patrikdufresne.com:/var/www/patrikdufresne/archive/minarca/nightly/
  - scp -o StrictHostKeyChecking=no $MINARCA_EXE_FILE www-data@kalo.patrikdufresne.com:/var/www/patrikdufresne/archive/minarca/nightly/

client_promote:
  stage: publish
  only:
  - tags
  environment:
    name: latest
    url: http://www.patrikdufresne.com/archive/minarca/minarca-latest-install.exe
  script:
  # Setup authentication
  - eval $(ssh-agent -s)
  - echo "$KALO_WWWDATA_PRIVATEKEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  # Publish to kalo
  - export MINARCA_DEB_FILE=$(ls -1 ./minarca-client*.deb)
  - export MINARCA_EXE_FILE=$(ls -1 ./minarca-client*.exe)
  - scp -o StrictHostKeyChecking=no $MINARCA_EXE_FILE www-data@kalo.patrikdufresne.com:/var/www/patrikdufresne/archive/minarca/
  - scp -o StrictHostKeyChecking=no $MINARCA_DEB_FILE www-data@kalo.patrikdufresne.com:/var/www/patrikdufresne/archive/minarca/
  - ssh -o StrictHostKeyChecking=no www-data@kalo.patrikdufresne.com ln -fs $(basename $MINARCA_EXE_FILE) /var/www/patrikdufresne/archive/minarca/minarca-latest-install.exe
  - ssh -o StrictHostKeyChecking=no www-data@kalo.patrikdufresne.com ln -fs $(basename $MINARCA_DEB_FILE) /var/www/patrikdufresne/archive/minarca/minarca-client_latest_all.deb

deploy_staging_sestican:
  stage: deploy
  image: ikus060/ansible
  variables:
    ANSIBLE_HOST_KEY_CHECKING: "False"
  environment:
    name: staging
    url: https://test.minarca.net
  before_script:
  - eval $(ssh-agent -s)
  - echo "$GITLAB_SSH_IDENTITY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  script:
  # Delete previous installation
  - ssh -o StrictHostKeyChecking=no root@sestican.patrikdufresne.com "! dpkg -s minarca-server || apt remove -y minarca-server --purge"
  - ssh -o StrictHostKeyChecking=no root@sestican.patrikdufresne.com "rm -Rf /etc/minarca/; rm -Rf /backups/"
  # Install minarca
  - export MINARCA_VERSION=$(cd minarca-server; python ./setup.py --version)
  - echo MINARCA_VERSION=$MINARCA_VERSION
  - export DEB_VERSION=$MINARCA_VERSION+stretch
  - echo DEB_VERSION=$DEB_VERSION
  - git clone "http://${GITLAB_USR}:${GITLAB_PWD}@git.patrikdufresne.com/pdsl/ansible-config.git"
  - cd ansible-config
  - ansible-playbook minarca.yml -i pdsl --extra-vars "ansible_user=root minarca_server_version=$DEB_VERSION" --limit sestican
  
deploy_prod_ranculos:
  stage: deploy
  image: ikus060/ansible
  when: manual
  only: 
  - tags
  - master
  variables:
    ANSIBLE_HOST_KEY_CHECKING: "False"
  environment:
    name: prod
    url: https://www.minarca.net
  before_script:
  - eval $(ssh-agent -s)
  - echo "$RANCULOS_ROOT_PRIVATEKEY" | tr -d '\r' | ssh-add - > /dev/null
  - echo "$MERCOR_ROOT_PRIVATEKEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  script:
  - export MINARCA_VERSION=$(cd minarca-server; python ./setup.py --version)
  - echo MINARCA_VERSION=$MINARCA_VERSION
  - export DEB_VERSION=$MINARCA_VERSION+stretch
  - echo DEB_VERSION=$DEB_VERSION
  - git clone "http://${GITLAB_USR}:${GITLAB_PWD}@git.patrikdufresne.com/pdsl/ansible-config.git"
  - cd ansible-config
  - ansible-playbook minarca.yml -i pdsl --extra-vars "ansible_user=root minarca_server_version=$DEB_VERSION" --limit ranculos,mercor
  
test_link_debian_stretch:
  image: debian:stretch
  stage: test-integration
  variables:
    MINARCA_REPOSITORYNAME: test-${CI_JOB_ID}
  script: 
  - export MINARCA_DEB_FILE=$(ls -1 ./minarca-client*.deb)
  - bash ./tests/install-client-deb.sh
  - bash ./tests/link-link-deb-linux.sh
  
test_link_debian_buster:
  image: debian:buster
  stage: test-integration
  variables:
    MINARCA_REPOSITORYNAME: test-${CI_JOB_ID}
  script: 
  - export MINARCA_DEB_FILE=$(ls -1 ./minarca-client*.deb)
  - bash ./tests/install-client-deb.sh
  - bash ./tests/link-link-deb-linux.sh

# This test is not working and fail because of issue with wine.
#test_link_win:
#  image: debian:buster
#  stage: test-integration
#  variables:
#    MINARCA_REPOSITORYNAME: test-${CI_JOB_ID}
#  allow_failure: true
#  script: 
#  - export MINARCA_EXE_FILE=$(ls -1 ./minarca-client*.exe)
#  - bash ./tests/install-client-win.sh
#  - bash ./tests/link-link-win.sh
  